Repository Telmate/terraform-provider-proxmox, pull requests merged in 2024-06, with the labels that each got.

#1038 fix: Pool typecast
  go.mod
  go.sum
  proxmox/resource_lxc.go
  proxmox/resource_pool.go
  proxmox/resource_vm_qemu.go
  proxmox/util.go
Labels: enhancement

#1039 feat: stop VM when deleting
  proxmox/resource_vm_qemu.go
Labels: enhancement

#1041 ci: bump workflow dependencies
  .github/workflows/go.yml
  .github/workflows/release.yml
Labels: workflow

#1047 Doc fix: proxmox_cloud_init_disk
  docs/resources/cloud_init_disk.md
Labels: documentation
