Repository Telmate/terraform-provider-proxmox, pull requests merged in 2024-04, with the labels that each got.

#948 Updating documentation and examples
  docs/guides/cloud_init.md
  docs/resources/cloud_init_disk.md
  examples/cloudinit_example.tf
Labels: documentation

#976 Update to docs for Disks.Virtio Block
  docs/resources/vm_qemu.md
Labels: documentation

#985 fix: `agent` can not be disabled
  .github/workflows/go.yml
  go.mod
  go.sum
  proxmox/resource_vm_qemu.go
Labels: bug

#990 Update cloud_init_disk.md
  docs/resources/cloud_init_disk.md
Labels: documentation

#987 fix: `machine` diff to `null`
  proxmox/resource_vm_qemu.go
Labels: bug

#988 fixes
  docs/resources/vm_qemu.md
  proxmox/provider.go
  proxmox/resource_lxc.go
  proxmox/resource_vm_qemu.go
Labels: bug

#994 Feature: Add `protection` property to the `resource_vm_qemu`
  docs/resources/vm_qemu.md
  examples/pxe_example.tf
  proxmox/resource_vm_qemu.go
Labels: enhancement

#989 Stale-bot exlusions
  .github/workflows/manage_issues.yml
Labels: workflow

#996 fix `qemu_os` diff to `null`
  proxmox/resource_vm_qemu.go
Labels: bug
