Repository Telmate/terraform-provider-proxmox, pull requests merged in 2024-09, with the labels that each got.

#1076 Fixes: panic `net0` does not exist
  proxmox/resource_vm_qemu.go
Labels: bug

#1079 Reimplement Serials
  docs/resources/vm_qemu.md
  go.mod
  go.sum
  proxmox/resource_vm_qemu.go
Labels: bug

#1080 feat `disk` schema
  docs/resources/vm_qemu.md
  proxmox/errors.go
  proxmox/resource_vm_qemu.go
Labels: enhancement

#1086 Refactor/use updated get method
  docs/resources/pool.md
  proxmox/resource_pool.go
Labels: enhancement

#1095 Fix: `disk` block diff
  docs/resources/vm_qemu.md
  proxmox/resource_vm_qemu.go
Labels: bug

#1109 add MTU documentation for qemu vm
  docs/resources/vm_qemu.md
Labels: documentation
