Repository Telmate/terraform-provider-proxmox, pull requests merged in 2024-11, with the labels that each got.

#1143 Rework QemuUSB
  docs/resources/vm_qemu.md
  go.mod
  go.sum
  proxmox/Internal/resource/guest/qemu/usb/schema.go
  proxmox/Internal/resource/guest/qemu/usb/sdk.go
  proxmox/Internal/resource/guest/qemu/usb/terraform.go
  proxmox/Internal/validator/validator.go
  proxmox/resource_vm_qemu.go
Labels: bug, enhancement

#1144 Add waring for `pm_parallel`
  docs/index.md
  proxmox/provider.go
Labels: bug, documentation

#1146 feature: possibility to clone vm based on id
  docs/resources/vm_qemu.md
  proxmox/resource_vm_qemu.go
Labels: enhancement

#1155 fix: regression #1154
  proxmox/resource_vm_qemu.go
Labels: bug

#1153 fix: fixes proxmox_storage_iso temp dir path
  proxmox/resource_storage_iso.go
Labels: bug

#1093 Enable starting an lxc container which was just created
  proxmox/resource_lxc.go
Labels: enhancement

#1120 fix: not attempting to get an IP due to cloud-init
  proxmox/Internal/resource/guest/qemu/disk/terraform.go
  proxmox/Internal/resource/guest/qemu/disk/terraform_disk.go
  proxmox/Internal/resource/guest/qemu/disk/terraform_disks.go
  proxmox/Internal/resource/guest/qemu/network/schema.go
  proxmox/Internal/resource/guest/qemu/network/sdk.go
  proxmox/Internal/resource/guest/qemu/network/terraform.go
  proxmox/heper_qemu.go
  proxmox/heper_qemu_test.go
  proxmox/resource_vm_qemu.go
  proxmox/util.go
Labels: bug

#1161 Fix: array out of bounds
  proxmox/Internal/resource/guest/qemu/network/schema.go
  proxmox/Internal/resource/guest/qemu/network/sdk.go
  proxmox/Internal/resource/guest/qemu/network/terraform.go
  proxmox/Internal/resource/guest/qemu/usb/schema.go
  proxmox/Internal/resource/guest/qemu/usb/sdk.go
  proxmox/Internal/resource/guest/qemu/usb/terraform.go
  proxmox/resource_vm_qemu.go
Labels: bug

#1162 Feat: Full Qemu PCI support
  docs/resources/vm_qemu.md
  go.mod
  go.sum
  proxmox/Internal/resource/guest/qemu/pci/schema.go
  proxmox/Internal/resource/guest/qemu/pci/sdk.go
  proxmox/Internal/resource/guest/qemu/pci/terraform.go
  proxmox/resource_vm_qemu.go
Labels: bug, enhancement

#1169 fix: devices not removed
  proxmox/Internal/resource/guest/qemu/pci/sdk.go
  proxmox/Internal/resource/guest/qemu/usb/sdk.go
Labels: bug

#1178 fix: provider insecure by default
  docs/index.md
  proxmox/provider.go
Labels: bug, enhancement

#1179 hotfix: panic, nil pointer dereference
  proxmox/Internal/resource/guest/qemu/cpu/terraform.go
Labels: bug

#1173 hotfix: vlan not set
  docs/resources/vm_qemu.md
  proxmox/Internal/resource/guest/qemu/network/sdk.go
Labels: bug
